import tkinter as tk
root = tk.Tk()
root.withdraw()
popup = tk.Toplevel(root)
popup.title('Test')
popup.geometry('300x200+200+200')
popup.resizable(False, False)
popup.attributes('-topmost', True)
popup.lift()
popup.focus_force()
popup.deiconify()
popup.update_idletasks()
print('started test popup')
label = tk.Label(popup, text='hello')
label.pack(padx=20, pady=20)
root.mainloop()
